create table if not exists users (
    id bigint generated by default as identity primary key,
    nickname varchar(50) not null unique,
    created_at timestamp not null
);

create table if not exists friends (
    id bigint generated by default as identity primary key,
    user_a bigint not null,
    user_b bigint not null,
    created_at timestamp not null,
    constraint ck_user_order check (user_a < user_b),
    constraint ck_friends_not_self check (user_a <> user_b),
    constraint ux_friends_pair unique (user_a, user_b),
    constraint fk_friends_a foreign key (user_a) references users(id),
    constraint fk_friends_b foreign key (user_b) references users(id)
);

create index if not exists ix_friends_a_created_at on friends(user_a, created_at desc);
create index if not exists ix_friends_b_created_at on friends(user_b, created_at desc);

create table if not exists friend_requests (
    id char(36) primary key,
    from_user_id bigint not null,
    to_user_id bigint not null,
    status varchar(16) not null,
    created_at timestamp not null,
    constraint ck_requests_not_self check (from_user_id <> to_user_id),
    constraint fk_requests_from_user foreign key (from_user_id) references users(id),
    constraint fk_requests_to_user   foreign key (to_user_id)   references users(id),
    constraint ux_requests_from_to_status unique (from_user_id, to_user_id, status)
);

create index if not exists ix_requests_to_created_at on friend_requests(to_user_id, created_at desc);

